name: Build kernel

on:
  push:


jobs:

  caprip:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Start
      run: |
        ./compile.sh caprip
